### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by seijikun** [php-sonic/php-sonic#1]
Hey! I'm the other guy who wrote a php client library for Sonic in parallel.
I guess it wouldn't make much sense maintaining two, so I would like to propose merging the libraries.

Some things coming to mind:
- I had a quick look at your library and saw, that our APIs are very similar
    - You have three flush methods (`flusho`, `flushb`, `flushc`), I have only one
    - Many of your methods don't return the results that Sonic reports. (e.g. `pop()` or the flush-methods)
- Is there a reason why you are using PHP's socket extension? The [stream API](https://www.php.net/manual/en/function.stream-socket-client.php) is built in and supports reading until a certain delimiter is found, which is probably more performant than your `readBuffer()` implementation.
- While my `SonicMessage` helper class might have been a bit overengineerd in the end, I think your ingest implementation is too easy. When starting a session with Sonic, Sonic tells one about the size of its receive buffer. If messages longer than this are sent to the server, Sonic will close the connection. Furthermore: If the input you get for either `push()`, `pop()`, `query()` or `suggest()` contains a newline, or a `"` your implementation should break. That may even be a security risk.
- You are often using `preg_match()` to parse responses. We probably need a benchmark for this, but I would guess that that is way more expensive than `strsplit()`.

What do you think?

**Comment by touhonoob** [comment]
Thanks for the detailed feedback. Please feel free to open pull requests.

**Comment by touhonoob** [comment]
resolved by #2
